osrf/mbzirc

mbzirc_ign/launch/spawn.launch.py
mbzirc_ros/CMakeLists.txt
mbzirc_ros/package.xml
mbzirc_ros/src/optical_frame_publisher.cc

Code adapted from [here](https://github.com/osrf/subt/blob/master/subt_ros/src/OpticalFramePublisher.cc) for ROS2.
Image data published by Ignition is in robot body frame (x forward, y left, z up) so added a `optical_frame_publisher` node that takes the existing msg data, convert it to optical frame (x right, y down, z forward) by broadcasting a new frame id with `_optical` suffix, and republishing the msg with updated `frame_id`.
To test, spawn the UAV as usual, and list the topics to see the new `*/optical/image_raw` and `*/optical/camera_info` topics. You can also echo the `*/optical/camera_info` topic to see that the its `frame_id` has the `_optical` suffix.
Signed-off-by: Ian Chen <ichen@openrobotics.org>

Add optical frame publisher

---

README.md
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/wam-v/model.sdf

Bridged topics for applying thruster cmd and joint pos cmd.
Note that the default ign topic name generated by `JointPositionController` (`/model/usv/joint/left_chasis_engine_joint/0/cmd_pos`) is actually an invalid name for a ROS topic. One of the name tokens starts with a numeric number, i.e. the joint index number `0`, which is not allowed in ROS as described in https://design.ros2.org/articles/topic_and_service_names.html. So the `ros_ign bridge` fails to create the ROS topic.
To workaround this issue, I had to specify a hardcoded `<topic>` for the `JointPositionController`. The downside of the hardcoded topic workaround is that there is no model namespacing so only one USV can subscribe to the joint pos cmd. For the case of MBZIRC, this is fine because there should only be one USV in …

Bridge thruster topics

---

mbzirc_ign/worlds/simple_demo.sdf

Added heightmap boundary using simple collision shapes so the USV does not go outside the heightmap.
To see the collisions, right click on the `heightmap_bounds` model, and select `View > Collisions` 
Signed-off-by: Ian Chen <ichen@openrobotics.org>

Add heightmap collision boundary

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/models/wam-v/model.sdf
mbzirc_ign/src/SimpleHydrodynamics.cc
mbzirc_ign/src/SimpleHydrodynamics.hh

This pull request builds atop of pull request #13, which should be merged first.
This pull request adds a new hydrodynamics plugin. It's attached to the WAM-V and should dissipate most of the oscillations of the vehicle.
For testing, launch the USV and observe that rocking reduces eventually compared with the version without this plugin. To make it a bit more evident, drop the WAM-V at a higher height.
```
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=wam-v type:=usv x:=15 y:=0 z:=-0.1 R:=0 P:=0 Y:=0
```
Feel free to send thruster commands as well, the vehicle should be stable:
```
ign topic -t /model/usv/joint/right_engine_propeller_joint/cmd_thrust -m ignition.msgs.Double -p …
```

Simple hydrodynamics plugin for the WAM-V

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/models/wam-v/model.sdf
mbzirc_ign/src/SimpleHydrodynamics.cc
mbzirc_ign/src/SimpleHydrodynamics.hh
mbzirc_ign/src/Surface.cc
mbzirc_ign/src/Surface.hh

We're moving the `Surface` plugin to mbzirc first since it still needs some work to make it generic enough for ign-gazebo. Currently this plugin assumes the USV has 2 hulls (i.e. catamaran) so it may not work for all surface vessels.
We can upstream this plugin once we make it more generic.
This PR removes the dependency on ign-gazebo's `surface_plugin` branch. ~However, it still needs some physics changes in ign-gazebo's `add_world_force` branch. Here's the PR: https://github.com/ignitionrobotics/ign-gazebo/pull/1279~. Update: ign-gazebo 6.4.0 has been released with changes needed by this PR.
Signed-off-by: Ian Chen <ichen@openrobotics.org>

Move Surface plugin to mbzirc

---

RELEASING.md

The PR adds a new file to describe the releasing process. It includes a bit of "what could go wrong" and if everything fails, how to release from a local system.

Add documentation about how to release MBZIRC

---

README.md
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/mbzirc_hexrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_quadrotor_base/model.sdf
mbzirc_ign/models/sensors/mbzirc_3d_lidar/model.config
mbzirc_ign/models/sensors/mbzirc_3d_lidar/model.sdf
mbzirc_ign/models/sensors/mbzirc_hd_camera/model.config
mbzirc_ign/models/sensors/mbzirc_hd_camera/model.sdf
mbzirc_ign/models/sensors/mbzirc_planar_lidar/model.config
mbzirc_ign/models/sensors/mbzirc_planar_lidar/model.sdf
mbzirc_ign/models/sensors/mbzirc_rgbd_camera/model.config
mbzirc_ign/models/sensors/mbzirc_rgbd_camera/model.sdf
mbzirc_ign/models/sensors/mbzirc_vga_camera/model.config
mbzirc_ign/models/sensors/mbzirc_vga_camera/model.sdf
mbzirc_ros/src/pose_tf_broadcaster.cc

Builds on #16 to provide user-configurable payload.
To launch a UAV with various payload configurations:
```
ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=3 y:=6 z:=0.12 R:=0 P:=0 Y:=0 slot0:=mbzirc_rgb_camera slot1:=mbzirc_planar_lidar
```
Where both UAVs now have 4 slots [`slot0`, `slot1`, `slot2`, `slot3`] and sensors are defined in `mbzirc_ign/models/sensors` to include [`mbzirc_3d_lidar`,  `mbzirc_hd_camera`,  `mbzirc_planar_lidar`,  `mbzirc_rgb_camera`, `mbzirc_rgbd_camera`,  `mbzirc_vga_camera`]
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Initial configurable payload support

---

.github/workflows/main.yml

The PR implements the release of the docker image into the osrf/mbzirc dockerhub. Requires #18 first.
It mainly reacts to tags with the form `dockerhub_release_*` where `*` is not used in the releasing, probably something meaningful for the person doing the release, a name, a date, whatever.
Steps:
1. Setup docker and sources
2. Use the `build.sh` script to create the docker image from the commit corresponding to the initial tag that triggered the action.
3. Create the docker tags: one is called `mbzric_sim_latest` and the other `mbzirc_sim_${timestamp}`. Timestamp includes date and hour-minute.
4. Login into the dockerhub (requires setup of credentials in this repo)
5. Push tags to the dockerhub
Tested in my fork:
* Action: https://github.com/j-rivero/mbzirc/runs/4809984061?check_suite_fo …

Add github action to release mbzirc docker image into dockerhub

---

mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/mbzirc_hexrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_hexrotor_base/model.sdf
mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_quadrotor_base/model.sdf

Signed-off-by: Ian Chen <ichen@openrobotics.org>
Adds 4 more sensor slots. Now a total of 8.
**Existing slots:**
slot 0: front
slot 1: rear
slot 2: top
slot 3 : bottom
**New slots:**
slot 4: left
slot 5: right
slot 6: bottom left
slot 7: bottom right
I also added some green box visuals for debugging the sensor positions. Uncomment them in the sdf to see their positions:

Add more sensor slots

---

.github/workflows/main.yml
README.md
docker/build.bash
docker/mbzirc_sim/Dockerfile

The PR replaces part of the code in the releasing process that was cloning the mbzirc repository inside the Docker image with the option of reusing the code present in the same local checkout of this repository.
This is useful to share the same Docker image between releasing and CI. As a side effect of this, the `build.sh` script must be called from the root of the repository so docker can `COPY` the source code.
A new release was tested in my fork https://github.com/j-rivero/mbzirc/runs/4967967660?check_suite_focus=true.

Simplifying release code

---

.github/workflows/integration_test.yaml

After some tests, I think that the best way of dealing with xvfb calls and containers is to call it directly in the container to avoid all the necessary mapping to make it work correctly.
The PR moves the call to be done in the docker run together with docker run that call colcon. I'm also including the same variables that we are using in ign-rendering testing.
With this setup I was able to make ign-rendering Camera test to pass https://github.com/osrf/mbzirc/runs/4982529291?check_suite_focus=true but DISPLAY test in this repository is still failing:
```
1: [ign gazebo -v 4 --iterations 20000 -s -r simple_demo.sdf-1] [Wrn] [Ogre2Heightmap.cc:118] Heightmap final sampling should be 2^n
1: [ign gazebo -v 4 --iterations 20000 -s -r simple_demo.sdf-1]  which differs from ogre1's 2^n+1
1: [ign …
```

Move xvfb to be called inside the docker container for tests

---

.github/workflows/integration_test.yaml
mbzirc_ign/worlds/empty_platform.sdf
mbzirc_ros/test/launch/test_ros_api.launch.py
mbzirc_ros/test/ros_api/test_ros_api.cc

Enabled rendering tests and mbzirc_ign integration tests.
Found that the rendering test segfault was due to issue with heightmap in CI machine. So I created a simpler world for testing that contains just a ground platform and loads all  ign-gazebo systems needed by the UAVs.

Enable more tests in CI

---

mbzirc_ign/models/usv/model.sdf.erb
mbzirc_ign/models/wam-v/model.sdf.erb

Updated rate of rotation to 15 degrees/s (0.2618 rad/s) based on spec: 
https://www.mbzirc.com/usv-details
To test:
```
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=usv type:=usv x:=15 y:=0 z:=-0.1 R:=0 P:=0 Y:=0
ros2 topic pub --once /usv/left/thrust/joint/cmd_pos std_msgs/msg/Float64 'data: -1.57079'
```

Update USV thruster joint rotation velocity

---

mbzirc_ign/worlds/simple_demo.sdf

max flight height allowed by [local regulations](https://u.ae/en/information-and-services/justice-safety-and-the-law/aviation-safety) is 400 feet / ~121.92 meters.
For this demo, we'll go with 400 ft from water plane (sea level)
The water plane in this world is at -1m, and the the collision boundary model is at -25m. So to get the ceiling collision to be at 121.92m from the water, its z pos is calculated as:
121.92 + 0.5 (half collision size) + 25 - 1 = 146.42m

Add a ceiling collision to simple demo world

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/src/GameLogicPlugin.cc
mbzirc_ign/src/GameLogicPlugin.hh
mbzirc_ign/test/test_game_logic.cc
mbzirc_ign/test/test_spawn_uav_battery.cc
mbzirc_ign/worlds/faster_than_realtime.sdf
mbzirc_ign/worlds/simple_demo.sdf

Added `GameLogicPlugin` with basic functionality for logging, starting and stopping a run, and publishing run status.
Added `test_game_logic` integration test.
Scoring functionality is not implemented yet.
There are 3 main plugin params:
* `<setup_duration_seconds>`: time allowed for teams to set up before starting a run
* `<run_duration_seconds>`: time limit for each run (count down starts when a run is "started")
* `<logging><path>`: Path to log files
**Starting and and finishing a run**
The actual procedure for starting  and stopping a run is still TBD. Currently service calls are provided to manually start and stop the run. To test:
```
ign service -s /mbzirc/start --reqtype ignition.msgs.Boolean --reptype ignition.msgs.Boolean --req …
```

Add basic GameLogicPlugin

---

mbzirc_ign/src/SimpleHydrodynamics.cc

Noticed that hydrodynamics also is missing a pause check. This will lead to weird behaviour when the usv is moving and we pause the simulation.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

Pause Hydrodynamics

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/models/usv/model.sdf.erb
mbzirc_ign/test/helper/TestFixture.hh
mbzirc_ign/test/test_spawn_usv_maxspeed.cc
mbzirc_ign/worlds/faster_than_realtime.sdf

This PR adds a limit to the USV thruster and some unit tests to test the limit. The USV model has also been made such that only the visual is rotated so that the hydrodynamics can be reasoned about. For derivation of the math see here: https://colab.research.google.com/drive/1xV0rw1rqBSU0RdVYTVUkHir7BHADQIWn?usp=sharing

Limits the maximum thrust to 8 knots

---

mbzirc_ign/worlds/coast.sdf

It requires https://github.com/ignitionrobotics/ign-gazebo/pull/1332 .
This pull request adds some basic autonomy to the Vessel A. For demo purposes, the vessel should loop between two points that are 50m. apart. Note that this vessel moves a 1 knot.

Autonomy for Vessel A

---

mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/usv/model.sdf.erb
mbzirc_ign/models/wam-v/model.sdf.erb

Transforms for the USV model were missing. I added the pose publisher system to the USV models and bridged them to the `/tf` and `/tf_static` topics
After spawning a USV, you should now see the `tf` topics.
To test:
```bash
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=usv type:=usv x:=15 y:=0 z:=0.3 R:=0 P:=0 Y:=0
ros2 topic list
ros2 run tf2_tools view_frames
evince frames.pdf
```

Publish USV transforms

---

docker/mbzirc_ros1_bridge/Dockerfile
docker/mbzirc_ros1_bridge/run_bridge.bash

Provide a base container with all necessary ROS 1 Noetic and ROS 2 Galactic dependencies to be able to run the ROS 1 bridge.  Summarizes some of the installation instructions from: https://github.com/osrf/mbzirc/wiki/Bridging-to-ROS1
To use (with the simulator running):
```
cd mbzirc/docker
./build.bash mbzirc_ros1_bridge
./run.bash mbzirc_ros1_bridge
```
In another terminal:
```
cd mbzirc/docker
./join.bash mbzirc_ros1_bridge
source /opt/ros/noetic/setup.bash
rostopic echo
```
I don't know if this is where this should ultimately live, but it was a convenient jumping-off location.
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Add a dockerfile for ROS 1 bridge

---

mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/simple_demo.sdf

Increased step size from 1ms to 4ms for performance reasons. Note 4ms is also the step size used in subt.
I didn't notice any unstable physics behavior. To verify update rate, you can spawn an UAV and monitor the `/tf` topic to see that it should now be  <= 250 Hz.
```bash
ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=0 y:=0 z:=1.05 R:=0 P:=0 Y:=0 slot0:=mbzirc_hd_camera
ros2 topic hz /tf
```

Increase physics step size

---

mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/mbzirc_fixed_wing/model.sdf.erb
mbzirc_ign/models/mbzirc_hexrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb
mbzirc_ign/models/usv/model.sdf.erb
mbzirc_ign/models/wam-v/model.sdf.erb

Depends on https://github.com/ignitionrobotics/ign-gazebo/pull/1342
We disabled publishing model ground truth pose data in the TF broadcaster by filtering out all incoming pose with the world name frame id [here](https://github.com/osrf/mbzirc/blob/main/mbzirc_ros/src/pose_tf_broadcaster.cc#L83-L86). However, it was found that the ground truth data is also published to the `/<namespace>/pose_static` ros2 topic. 
This PR disables publishing top level model pose by configuring the pose-publisher system to publish only nested model pose by setting the parameter `publish_model_pose` (added in https://github.com/ignitionrobotics/ign-gazebo/pull/1342) to false.
to test:
```bash
ros2 launch mbzirc_ign …
```

Disable publishing model ground truth pose

---

mbzirc_ign/worlds/coast.sdf

Depends on https://github.com/ignitionrobotics/ign-gazebo/pull/1349
Added ~4~ ~5~ 6 more target vessels with surface and hydrodyamics plugns. Wind effect should also be enabled.
Added arbitrarily selected way points for each vessel. I had to add a parameter to the trajectory follower system to force the angular velocity to be zero once target bearing is reached (https://github.com/ignitionrobotics/ign-gazebo/pull/1349). Otherwise the vessels will keep rotating on the spot due to overshooting behavior. I don't know if could be reduced by tuning the hydrodynamics coefficients to damp the rotational movements. Side note, I also tried adding a PID controller for bearing control in the trajectory controller but overshoot still occurs - it could …

Add 6 more target vessels to coast environment

---

README.md
mbzirc_ign/models/mbzirc_fixed_wing/model.sdf.erb
mbzirc_ign/models/mbzirc_fixed_wing_base/model.sdf
mbzirc_ign/worlds/empty_platform.sdf

Changes:
* Added sensor mount points
* tweaked README.md instructions and added a note to run `rosdep` to make sure the user has mavros package dependency
To test:
```
ros2 launch mbzirc_ign spawn.launch.py name:=zephyr world:=simple_demo model:=mbzirc_fixed_wing type:=uav x:=0 y:=0 z:=4 slot0:=mbzirc_hd_camera  slot1:=mbzirc_hd_camera slot2:=mbzirc_hd_camera slot3:=mbzirc_hd_camera slot4:=mbzirc_hd_camera slot5:=mbzirc_hd_camera slot6:=mbzirc_hd_camera slot7:=mbzirc_hd_camera
```
Then use the `Image Display` ign-gazebo GUI plugin to check all camera views

Support mounting sensors on fixed wing UAV

---

mbzirc_ign/models/usv/model.sdf.erb

Updated to match the values given.
I also merged the `base_collision` link into `base_link` to remove an extra link that uses the default (incorrect) inertia values (ixx =1, iyy =1, izz =1).
After setting the given inertia values, I noticed more rocking movement so I tweaked the hydrodynamics coefficients to help damp this motion.

Update USV inertial values

---

mbzirc_ign/src/GameLogicPlugin.cc
mbzirc_ign/test/test_game_logic.cc
mbzirc_ign/worlds/empty_platform.sdf
mbzirc_ros/CMakeLists.txt
mbzirc_ros/launch/competition.launch.py
mbzirc_ros/package.xml
mbzirc_ros/test/launch/test_ros_api.launch.py
mbzirc_ros/test/ros_api/test_ros_api.cc

Added a new launch file for bringing up ign-gazebo along with ros2 bridges for competition topics, including:
* `/mbzirc/score` - current score which is sim time + time penalty
* `/mbzirc/phase` - string msg containing info on current phase of the competition: `setup`, `started`, `vessel_id_success`, `small_object_id_success`, `large_object_id_success`
* `/mbzirc/run_clock` - count down of time remaining.
To test, launch simple_demo world using the new launch file and echo the topics using ros2:
```
ros2 launch mbzirc_ros competition.launch.py ign_args:="-v 4 -r simple_demo.sdf"
ros2 topic echo /mbzirc/score
ros2 topic echo /mbzirc/phase
ros2 topic echo /mbzirc/run_clock
```

Bridge competition topics

---

mbzirc_ign/src/GameLogicPlugin.cc
mbzirc_ign/test/test_game_logic.cc
mbzirc_ign/worlds/empty_platform.sdf
mbzirc_ros/CMakeLists.txt
mbzirc_ros/launch/competition.launch.py
mbzirc_ros/package.xml
mbzirc_ros/test/launch/test_ros_api.launch.py
mbzirc_ros/test/ros_api/test_ros_api.cc

There are 2 geofences for the competition area. If a robot moves outside of the first geofence, a time penalty is given (implemented in https://github.com/osrf/mbzirc/pull/41). 
This PRs adds the 2nd / outer geofence. If a robot moves outside of this geofence, ~a `HaltMotion` component is added to the robot model which will lock its joints and stop its motion - similar to what a 'kill switch' does in the real world.~  the robot is made static. 
* Note: I ran into a crash with ode collision checking error when quadrotor fell from sky and crashing into boundary collisions at high speed, so now just freezing the robot instead of locking its joints with `HaltMotion` component
To test:
1. launch coast world and spawn a quadrotor
```sh
ros2 …
```

Stop robot motion when it moves out of 2nd geofence 

---

mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb
mbzirc_ign/src/GameLogicPlugin.cc
mbzirc_ign/test/test_game_logic.cc
mbzirc_ign/worlds/empty_platform.sdf
mbzirc_ign/worlds/faster_than_realtime.sdf
mbzirc_ros/CMakeLists.txt
mbzirc_ros/launch/competition.launch.py
mbzirc_ros/package.xml
mbzirc_ros/test/launch/test_ros_api.launch.py
mbzirc_ros/test/ros_api/test_ros_api.cc

Depends on https://github.com/ignitionrobotics/ign-gazebo/pull/1381
Targets are to be reported by labeling their location in a live video stream. This PR adds the following functionality:
* ign service to indicate a stream has started
* ign service for reporting the target location (image 2d pos) in the image stream
* validate the reported image pos contains a valid target
The GameLogic plugin does not actually process any incoming video images, e.g. no object recognition or image processing, etc but instead it uses the rendering engine to check if target objects are in the camera view (by checking target is within frustum and projecting ray to see if it hits the target)
To test, I find it easiest to make the UAV static first so it does not fall when we hover it over the target, e.g. …

Support validating target reports through image stream

---

mbzirc_ign/config/single_usv_config.yaml
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/mbzirc_usv_base/model.sdf
mbzirc_ign/models/usv/model.sdf.erb
mbzirc_ign/src/mbzirc_ign/model.py
mbzirc_ign/src/mbzirc_ign/test_model.py

Added support for USVs to carry 4 sensor payloads. The 4payloads are:
* slot0: front (on top platform)
* slot1: rear (on top platform)
* slot2: left (attached to side of hull)
* slot3: right (attached to side hull)
The green boxes below visualizes the location of the senors on the USV:
As an example for test, the commands below spawns the usv with 4 cameras in the simple demo world. The camera in slot3 (right) is oriented to face forward.
```
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=usv type:=usv x:=15 y:=0 z:=0.3 R:=0 P:=0 Y:=0 arm:=mbzirc_oberon7_arm gripper:=mbzirc_oberon7_gripper slot0:=mbzirc_hd_camera …
```

Add sensor payloads to USV

---

mbzirc_ign/launch/spawn.launch.py

Depends on https://github.com/ignitionrobotics/ros_ign/pull/225
Enable laziness to improve performance
Tested with 1 quadrotor and 8 hd cameras. With this change, the RTF remains at 9x% after spawning the UAV. As I subscribe to camera image streams, the RTF drops by a few % after each subscription, eventually coming down to 4x % after 8 subscriptions

Enable lazy subscriber in all ros_ign parameter bridges

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/models/mbzirc_fixed_wing/model.sdf.erb
mbzirc_ign/models/mbzirc_fixed_wing_base/model.sdf
mbzirc_ign/package.xml
mbzirc_ign/src/FixedWingController.cc
mbzirc_ign/test/test_fixed_wing.cc
mbzirc_ign/test/test_gripper.cc
mbzirc_ign/worlds/coast.sdf
mbzirc_ros/package.xml

This commit adds support for takeoff behaviour in the flight controller. I also discovered that the pitch axis was flipped. This PR fixes it as well. It also removes the dependency on ros within the ignition plugin. A separate ros bridge was added in #81. The aim is to move that to another bridge node.
You will need 3 terminals. In one terminal start gazebo.
```
ign gazebo coast.sdf
```
In another spawn the plane:
```
ros2 launch mbzirc_ign spawn.launch.py name:=zephyr world:=coast model:=mbzirc_fixed_wing type:=uav x:=-1500 y:=0 z:=5
```
Finally command the plane to take off:
```
ign service -s /zephyr/cmd/takeoff  --reqtype ignition.msgs.Float_V --reptype ignition.msgs.Boolean -r "data: [0.2, 40]" --timeout 10000000
```
The plane should start flying. The format of the last service is …

Adds support for takeoff

---

mbzirc_ign/src/mbzirc_ign/model.py

Since we have an attitude controller, it does not make sense to bridge low level controls to teams for fixed wings as the commands will be over written by the attitude controller. Instead they should publish messages to attitude controllers.
An alternative to this PR would be to have an enable/disable flag for the ttitude controller and bridge that over.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

Don't bridge low level controls for fixed wings

---

mbzirc_ign/src/GameLogicPlugin.cc

When the target vessel is identified, it should come to a stop (but still affected by waves) so that the teams can proceed with the intervention task. This PR adds a publisher to the game logic plugin to publish a message to pause the trajectory follower system when target vessel is identified.
To test:
1. Start sim paused
```
ros2 launch ros_ign_gazebo ign_gazebo.launch.py ign_args:="-v 4  coast.sdf
```
1. Spawn a quadrotor with downward looking camera
```
ros2 launch mbzirc_ign spawn.launch.py name:=quadrotor_1 world:=simple_demo model:=mbzirc_quadrotor type:=uav x:=-1500 y:=0 z:=4.3 R:=0 P:=0 Y:=0 slot3:=mbzirc_hd_camera
```
1. Move the quadrotor over Vessel A
```
ign service -s /world/coast/set_pose --reqtype ignition.msgs.Pose …
```

Pause target vessel trajectory following when identified

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/test/test_spawn_usv_maxspeed.cc
mbzirc_ign/worlds/test/usv_max_speed.sdf

Two tests were causing an :x: in the CI. The first was `test_spawn_usv_maxspeed`. This PR fixes `test_spawn_usv_maxspeed` by creating a seperate test world for it without the gamelogic plugin. This is because the gamelogic plugin was terminating the test before it could be completed. I also increased the test timeouts.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

Fixes CI tests

---

mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/faster_than_realtime.sdf
mbzirc_ign/worlds/simple_demo.sdf

This pull request removes the rocking that some of the vessels where experiencing in the ocean.
**How to test it?**
* Run the coast environment:
```
ros2 launch mbzirc_ros competition_local.launch.py ign_args:="-v 4 -r coast.sdf"
```
Look at vessel A. Before this PR, the boat starts rocking around 1min 20s sim time. It shouldn't happen now. Let it run for some time and verify that the vessel never has a rocking behavior and it starts moving to the waypoints. Additionally watch other vessels and confirm that they also move eventually.
**Here's the long explanation about the rocking:**
The rocking was introduced when the `TrajectoryFollower` plugin was using the `<zero_vel_on_bearing_reached>` option. The problem is the following: The vessel starts rotating to be aligned with the next …

Fix vessel rocking

---

mbzirc_ign/config/single_usv_with_arm_gripper_config.yaml
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/launch/spawn_config.launch.py
mbzirc_ign/models/mbzirc_usv_base/model.sdf
mbzirc_ign/models/usv/model.sdf.erb
mbzirc_ign/src/mbzirc_ign/model.py

Added an extra parameter `arm_slot` that can be used to attach the arm into a custom mounting slot.
Here's the accompanying tutorial:
https://github.com/osrf/mbzirc/wiki/Custom-Arm-Mount
The tutorials shows hot to create a new custom arm slot. Follow the tutorial and you should be able to spawn the arm in the right side of the USV. The default behavior (no `arm_slot` parameter) should still work.

Arm custom arm mounting slots

---

mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/simple_demo.sdf

Adds the `<disable_on_drained_battery>` parameter in sensors system introduced in https://github.com/gazebosim/gz-sim/pull/1385
This sets the sensors active state of `false` to prevent them from publishing data once the battery is completely drained.

Disable sensors on drained battery

---

mbzirc_ign/launch/spawn_config.launch.py

Ported changes from https://github.com/osrf/mbzirc/pull/97 to `spawn_config.launch.py`. The changes are mainly for separating the logic for spawning robots models from spawning bridges in preparation for running the simulation on multiple machines
Easier to review without whitespace diff:
https://github.com/osrf/mbzirc/pull/107/files?w=1
To test:
```sh
ros2 launch mbzirc_ign spawn_config.launch.py world:=simple_demo config_file:=./src/mbzirc/mbzirc_ign/config/single_uav_config.yaml sim_mode:=sim
ros2 launch mbzirc_ign spawn_config.launch.py world:=simple_demo config_file:=./src/mbzirc/mbzirc_ign/config/single_uav_config.yaml sim_mode:=bridge
```
To spawn …

Update spawn_config to support spawning robots and bridges separately

---

mbzirc_custom/mbzirc_naive_radar/src/NaiveRadar.cc
mbzirc_ign/CMakeLists.txt
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/mbzirc_suction_gripper/model.sdf.erb
mbzirc_ign/models/static_arm/model.sdf.erb
mbzirc_ign/src/SuctionGripper.cc
mbzirc_ign/src/mbzirc_ign/bridges.py
mbzirc_ign/src/mbzirc_ign/model.py
mbzirc_ign/worlds/test/simple_arm_demo.sdf

This modifies the suction gripper to use an array with 5 contact sensors (displayed below) ![image](https://user-images.githubusercontent.com/279701/167935290-6535070e-95f7-49bb-90a3-e8ca9950e862.png)
In order for suction to engage, the center and one outside contact point (left/right/up/down) must be engage OR two opposite outside contact points must be engaged (left + right/up + down).  This makes it so the gripper is perpendicular to a surface before gripping can be engaged.
To test, I have added a world with just a simple manipulation setup:
```
ros2 launch ros_ign_gazebo ign_gazebo.launch.py ign_args:="-v 4 -r test/simple_arm_demo.sdf"
```
And spawn an arm: 
```
ros2 launch mbzirc_ign spawn.launch.py name:=simple_arm world:=simple_demo model:=static_arm arm:=mbzirc_oberon7_arm …
```

Change suction gripper to utilize contact point array

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/test/test_gripper.cc
mbzirc_ign/worlds/test/suction_gripper.sdf

Added mini suction gripper to the arm in the test:
It was a bit difficult to have contacts on more than one gripper cylinder collisions so I had to tune a few params around.

Fix suction gripper test

---

mbzirc_custom/mbzirc_naive_spinning_radar/models/sensors/mbzirc_naive_spinning_radar/model.sdf
mbzirc_custom/mbzirc_point_lidar/models/sensors/mbzirc_point_lidar/model.sdf
mbzirc_ign/models/coast_waves/model.sdf
mbzirc_ign/models/sensors/mbzirc_3d_lidar/model.sdf
mbzirc_ign/models/sensors/mbzirc_planar_lidar/model.sdf
mbzirc_ign/models/waves/model.sdf

Depends on:
* https://github.com/gazebosim/sdformat/pull/1015
* https://github.com/gazebosim/gz-rendering/pull/625
* https://github.com/gazebosim/gz-sensors/pull/224
Sets visibility mask to lidar and visbility flags to the waves model so that the lidar sensor does not detect waves.
Before - lidar point cloud visualization shows points on the surface of the water plane:
After - lidar no longer detects waves:

Omit waves from lidar returns

---

mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/simple_demo.sdf

I just bumped the tx power used in the comms from 20 to 25 dBm to increase the communication range a bit.
Signed-off-by: Carlos Agüero <caguero@openrobotics.org>

Bump tx power

---

mbzirc_ign/models/mbzirc_oberon7_gripper/model.sdf.erb

I replaced the `FingerTip.dae` with 10 simple shape collisions per fingertip. 
Collisions from `1` to `7` go in the side that touches the object to be picked up.
Collisions `8` to `10` are on the exterior side of the fingertip.

Simple colliders for the gripper

---

mbzirc_ign/models/mbzirc_usv_base/model.sdf

Fixes https://github.com/osrf/mbzirc/issues/117
Updated joint limits to match the rotation angle in the USV spec (at bottom of page): https://www.mbzirc.com/grand-challenge#loop-10
I also brought back the changes for the rotation speed from https://github.com/osrf/mbzirc/pull/33 which were probably lost during the last refactor.

Update thruster joint rotation to match spec

---

mbzirc_ign/launch/competition.launch.py
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/launch/spawn_config.launch.py
mbzirc_ign/src/mbzirc_ign/launch.py

Supports starting the simulation environment, spawning models and all supporting infrastructure with a single entry point:
For example spawning the coast with a single hexrotor.
```
ros2 launch mbzirc_ign competition.launch.py world:=coast config_file:=/home/mjcarroll/workspaces/mbzirc/src/mbzirc/mbzirc_ign/config/coast/hexrotor.yaml
```
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Add single entry point competition launch

---

mbzirc_ign/config/single_usv_with_arm_gripper_config.yaml
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/models/mbzirc_oberon7_arm/model.sdf.erb
mbzirc_ign/models/usv/model.sdf.erb
mbzirc_ign/src/mbzirc_ign/bridges.py
mbzirc_ign/src/mbzirc_ign/model.py
mbzirc_ign/src/mbzirc_ign/payload_bridges.py
mbzirc_ign/src/mbzirc_ign/test_bridges.py
mbzirc_ign/src/mbzirc_ign/test_model.py
mbzirc_ros/CMakeLists.txt
mbzirc_ros/test/launch/test_ros_api.launch.py
mbzirc_ros/test/ros_api/test_ros_api.cc

This PR adds support for configuring the sensor payload on the wrist of the robot arm. This removes the hardcorded VGA camera and lets user specify the sensor to use from the list of available sensor models in mbzirc. Only 1 sensor payload is allowed.
The two new args are:
* `arm_payload_slot0`
* `arm_payload_slot0_rpy`
here is an example of spawning a USV with lidar:
```sh
ros2 launch mbzirc_ros competition_local.launch.py ign_args:="-v 4 -r simple_demo.sdf"
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=usv x:=15 y:=0 z:=0.3 R:=0 P:=0 Y:=0 arm:=mbzirc_oberon7_arm arm_payload_slot0:=mbzirc_planar_lidar arm_payload_slot0_rpy:='0 -10 0' slot0:=mbzirc_hd_camera
```

Support configuring sensor payload on arm

---

mbzirc_ign/src/mbzirc_ign/model.py
mbzirc_ros/CMakeLists.txt
mbzirc_ros/src/usv_bridge.cc

* Be explicit about ignition math in cmake
* Make use of namespaces rather than passing model name
* Push commands into namespace (eg `/usv/cat/cmd_pod` rather than `/cat/cmd_pod`)
* Prefer const ref callbacks.
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Suggestions to #131

---

mbzirc_ign/worlds/coast.sdf

Fixes #139 
Fix system params in coast world, which seem like they are from a bad merge. The `tx_power` should now be 25 as of https://github.com/osrf/mbzirc/pull/113

Fix coast world systems

---

mbzirc_ign/launch/multi_uav_drag_demo.launch.py
mbzirc_ign/launch/multi_uav_drag_with_handles_demo.launch.py
mbzirc_ign/launch/multi_uav_lift_demo.launch.py

Fix style issues in uav drag launch files

---

mbzirc_ign/models/mbzirc_hexrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb

Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
Since the gripper models are now named with the models they attach to, we should check for `include?` in the template.

Checking if gipper model name is a substring instead of direct compare

---

mbzirc_custom/mbzirc_naive_3d_scanning_radar/models/sensors/mbzirc_naive_3d_scanning_radar/model.sdf
mbzirc_custom/mbzirc_naive_spinning_radar/CMakeLists.txt
mbzirc_custom/mbzirc_naive_spinning_radar/hooks/resource_paths.dsv.in
mbzirc_custom/mbzirc_naive_spinning_radar/hooks/resource_paths.sh
mbzirc_custom/mbzirc_naive_spinning_radar/models/sensors/mbzirc_naive_spinning_radar/model.config
mbzirc_custom/mbzirc_naive_spinning_radar/models/sensors/mbzirc_naive_spinning_radar/model.sdf
mbzirc_custom/mbzirc_naive_spinning_radar/package.xml
mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/simple_demo.sdf

Restores the spinning radar as the [custom sensor tutorial](https://github.com/osrf/mbzirc/wiki/Custom-Sensors#adapting-existing-sensor) that depends on it
I also updated some of the 3d scanning radar model's params

Move scanning radar to new model

---

mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/simple_demo.sdf
mbzirc_ign/worlds/test/multi_drone_lift.sdf

Recent changes to the large object models caused the RTF to drop to 4x% in the coast environment for me. This PR adds another joint between the objects and the vessel to improve performance. Note that the objects are already chained together using detachable joints and were previously just resting on top of the vessel. The change brings the RTF to 7x-8x% for me.
The objects are detached when the vessel is identified as described in https://github.com/osrf/mbzirc/wiki/Running-the-coast-environment#objects-on-vessel

Attach all objects to vessel

---

docker/compose/README.md
docker/compose/cyclonedds.xml
docker/compose/gen_docker_compose.py
docker/mbzirc_seed/Dockerfile
docker/mbzirc_seed/run_solution.bash
mbzirc_ign/launch/competition.launch.py
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/launch/spawn_config.launch.py
mbzirc_ign/src/mbzirc_ign/launch.py

Add a `gen_docker_compose.py` python script to generate a docker compose yaml file for launching simulation, bridge, and team containers locally. 
The script has 2 required args:
* `--config <path_to_team_config_file>`: Team configuration yaml file containing the robots and sensors to spawn into simulation
* `--image <team_image>`: Name of team solution docker image
Other optional args:
* `--world <world_name>`: Name of the world to launch. Defaults to `coast`
* `--headless <headless>`: `1` or `0`. `1` (True) to launch simulation headless (no GUI). Defaults to `0`.
* `--out <output_file_path>`: Path of output docker compose yaml file. Defaults to `mbzirc_compose.yaml`.
To test launching the containers with docker compose, you'll need to build the docker images locally from this branch: …

Add script to generate docker compose file for running simulation on local machine

---

mbzirc_ign/launch/competition.launch.py
mbzirc_ign/launch/spawn.launch.py
mbzirc_ign/launch/spawn_config.launch.py

There seems to be a bug when launching the simulation via `competition.launch.py` at least. The problem is that some of the bridges are not started.
I think that this is because the bridges are only started when `sim_mode` is equal to `bridge`. However that default `sim_mode` is `full`, which should also start the bridges.
How to test it?
Launch the simulation:
```
ros2 launch mbzirc_ign competition.launch.py world:=coast config_file:=`ros2 pkg prefix mbzirc_ign`/share/mbzirc_ign/config/coast/config_team.yaml
```
Check the ROS 2 topics:
```
ros2 topic list
```
You should see:
```
/clock
/mbzirc/phase
/mbzirc/run_clock
/mbzirc/score
/mbzirc/target/stream/status
```

Launch bridges when sim_mode is 'full'

---

mbzirc_custom/mbzirc_naive_3d_scanning_radar/models/sensors/mbzirc_naive_3d_scanning_radar/model.sdf
mbzirc_custom/mbzirc_naive_3d_scanning_radar/src/Naive3dScanningRadar.cc

After doing more testing with the radar implementation, we noticed that with the current angular resolution, it's very difficult to detect vessels, especially if they are far away. In the real world, the radar beam is more of a cone shape as opposed to a thin ray. Distant objects will still be detected but just with higher error. 
This PR changes the way we are sampling range output from the lidar. Instead of changing the implementation to use a cone, we use a lidar with a higher sample count but then downsample from the output values, i.e. For every cluster of points, we take it's average range values. 
With this change, the radar is able to detect a few vessels at a time. Over time, it should be able to detect all vessels. It may be faster if the user rotates the vessel to get a better …

compute range values from cluster of points

---

mbzirc_ign/models/mbzirc_usv_base/model.sdf

https://github.com/osrf/mbzirc/pull/119 updated the thruster rotation limits to match the image on the [website](https://www.mbzirc.com/grand-challenge#loop-10) (near the bottom). However, it was just confirmed that the image on the website is incorrect. So this PR reverts limits back to -90 to +90.
To test:
```
ros2 launch mbzirc_ros competition_local.launch.py ign_args:="-v 4 -r simple_demo.sdf"
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=usv type:=usv x:=15 y:=0 z:=0.3 R:=0 P:=0 Y:=0
ros2 topic pub --once /usv/left/thrust/joint/cmd_pos std_msgs/msg/Float64 'data: -1'
ros2 topic pub --once /usv/left/thrust/joint/cmd_pos std_msgs/msg/Float64 'data: 1'
```

Revert thruster joint limits

---

mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/playback.sdf
mbzirc_ign/worlds/simple_demo.sdf

Adds log recording to `simple_demo.sdf` and `coast.sdf` world.
To test:
1. Launch coast world with a few robots and let it run for some time
```
ros2 launch mbzirc_ign competition.launch.py world:=coast config_file:=`ros2 pkg prefix mbzirc_ign`/share/mbzirc_ign/config/coast/config_team.yaml
```
1. Close the simulator. Verify that the log is created: `/tmp/ign/mbzirc/playback/state.tlog`
1. Launch simulator again in playback mode
```sh
ign gazebo -v 4 `ros2 pkg prefix mbzirc_ign`/share/mbzirc_ign/worlds/playback.sdf
```

Enable log recording

---

mbzirc_custom/mbzirc_naive_3d_scanning_radar/src/Naive3dScanningRadar.cc

The radar works by using downsampling from raw lidar range values. When a number of valid consecutive hits / range values are found, it generates a radar reading with a range value. I noticed that the count of valid range values are only incremented on second valid range value. This PR fixes the issue. Before this change, we need at least 2 valid rays to generate a radar reading. After this change, we only need 1 valid lidar ray to generate a radar reading.
Given that the raw lidar rays are already dense, we usually get more than 1 consecutive hits. The improvement in the number of valid radar returns is small.
To test, launch coast world and spawn a USV with the radar model:
```
ros2 launch mbzirc_ros competition_local.launch.py …
```

Fix radar sample count

---

mbzirc_ign/CMakeLists.txt
mbzirc_ign/src/Components.hh
mbzirc_ign/src/GameLogicPlugin.cc
mbzirc_ign/src/MbzircTypes.hh
mbzirc_ign/src/SimpleHydrodynamics.cc
mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/faster_than_realtime.sdf
mbzirc_ign/worlds/simple_demo.sdf
mbzirc_ros/test/ros_api/test_ros_api.cc

Adds checking for competition configuration issues.
* There can be no more than 30 rendering sensors
* There can be no more than 1 USV
* All vehicles must be spawned within the start area.
The configuration is checked at the time the competition is started.
To test, start a world:
```
ros2 launch mbzirc_ros competition_local.launch.py ign_args:="-v 4 -r simple_demo.sdf"
```
Spawn a USV outside of the start area
```
ros2 launch mbzirc_ign spawn.launch.py name:=usv world:=simple_demo model:=mbzirc_usv type:=usv x:=-40 y:=2 z:=1.05 R:=0 P:=0 Y:=0 slot0:=mbzirc_hd_camera
```
Or spawn 2 usvs
And then change the competition phase:
```
ign service -s /mbzirc/skip_to_phase --reqtype ignition.msgs.StringMsg --reptype ignition.msgs.Boolean --timeout 300 --req 'data: "started"'
```
And an error will …

Add competition auditing to the game logic system

---

mbzirc_ign/config/coast/config_team.yaml
mbzirc_ign/src/mbzirc_ign/model.py
mbzirc_ign/src/mbzirc_ign/test_model.py

When launching sim with a config file, the payload bridge mapping string was generated incorrectly. This issue does not exist when launching sim and spawning robots manually.
To test, launch coast world with `config_team.yaml`:
```
ros2 launch mbzirc_ign competition.launch.py world:=coast config_file:=`ros2 pkg prefix mbzirc_ign`/share/mbzirc_ign/config/coast/config_team.yaml
```
Verify that you should now be able to see data in  the `/quadrotor_1/slot3/image_raw` topic, e.g using `rqt_image_view`
```
ros2 run rqt_image_view rqt_image_view
```
and select the `/quadrotor_1/slot3/image_raw` topic
Before this change, the slot number in the ros2 topic string was incorrectly generated as `slot0` when it should be `slot3`.

Fix payload bridge mapping when loading from config file

---

docker/cloudsim_bridge/run_bridge.bash

When launching Cloudsim bridges and field computers (FCs) on networks without multicast, it is necessary to configure the `cyclonedds.xml` file with peer information so that bridges and FCs can discover each other and exchange information.
The `cyclonedds.xml` configuration file requires a `<Peer>` entry with the IP of the peer on both containers looking to communicate using unicast. Each container contains the IP address of the other container it wants to connect to. 
When launching in the cloud, IPs are not fixed, and they are not available until the container starts running, which is problematic due to the inherent cycle in the peer configuration. It is not possible to configure a container before launching, and it is not possible to launch a container before it is configured.
An …

Add stall option to cloudsim_bridge docker entrypoint

---

mbzirc_ign/models/mbzirc_hexrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb
mbzirc_ign/models/mbzirc_suction_gripper_light/model.config
mbzirc_ign/models/mbzirc_suction_gripper_light/model.sdf.erb
mbzirc_ign/src/mbzirc_ign/model.py
mbzirc_ign/src/multicopter_control/LeeVelocityController.cc
mbzirc_ign/src/multicopter_control/LeeVelocityController.hh
mbzirc_ign/src/multicopter_control/MulticopterVelocityControl.cc
mbzirc_ign/src/multicopter_control/MulticopterVelocityControl.hh

Alternative to #194 
In comparison to #194, this PR adds the proposed changes while preserving existing behavior of multicopters with the original suction grippers by
* adding a new `mbzirc_suction_gripper_light` model with the proposed mass changes
* adding a parameter to multicopter velocity controller plugin to enable/disable rotor thrust computation changes
* the updated controller with the thrust changes is only enabled if a quad / hexrotor is equipped with the lightweight version of the suction gripper
Some minor issues I noticed when testing the lightweight gripper:
* a quadrotor with light weight suction gripper and no payload drifts slowly upwards in z when set to hover, i.e. linear vel set to zero
* a hexrotor with light weight …

Add light weight suction gripper with updated multicopter velocity controller

---

mbzirc_ign/src/BaseStation.cc
mbzirc_ign/src/GameLogicPlugin.cc

Fixes https://github.com/osrf/mbzirc/issues/193
Depends on https://github.com/gazebosim/gz-rendering/pull/690
Currently target reporting only works with video stream from one camera. This PR adds support so that target report can be done from different cameras, e.g. verify vessel report from slot0 of quad_1 and then verify small object report from slot3 of quad_2.
To test:
1. Apply the following patch make the quadrotor static and move Vessel B closer to coast and make it static so it's easier to test target reporting:
<details><summary>patch</summary>
```diff
diff --git a/mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb b/mbzirc_ign/models/mbzirc_quadrotor/model.sdf.erb
index a16a8de..0cde58b 100644
--- …
```

Support changing video streams when reporting targets

---

mbzirc_ign/src/GameLogicPlugin.cc
mbzirc_ros/CMakeLists.txt
mbzirc_ros/package.xml
mbzirc_ros/src/video_target_relay.cc

The changes enable 2 sets of images to be saved when a target is reported:
1. An image from the image stream transmitted by the user (over comms) is saved.
* I added a new dependency, `cv_bridge`, for saving `sensor_msgs::msgs::Image` to file. So you'll need to run `rosdep` again or `apt install ros-galactic-cv-bridge` if you don't have this package.
* This image file is saved  to `~/.ros/mbzirc`. Reason is that the video relay node is run on the bridge container on the cloud, and in this container we are uploading the `.ros` directory to s3. 
* Only the last image of a particular target type is saved, e.g. if the user reported small target vessel twice, the last one will be saved.
3. An image is saved by the `GameLogicPlugin`. The image …

Save target report images

---

mbzirc_ign/worlds/coast.sdf
mbzirc_ign/worlds/coast_cloud.sdf
mbzirc_ign/worlds/simple_demo.sdf

Depends on https://github.com/gazebosim/gz-sim/pull/1636
This reduces the rate at which states are being recorded. Main motivation is to reduce log size and and impact on performance during the run. Currently we are getting >18GB log files for a full 60min run.
In my local testing, before this change, for a run of 30s, the state.tlog is roughly ~132MB when testing locally with the mbzirc_seed solution. After changing the recording period to 8ms (double the 4ms step size), the state.tlog is now roughly ~66MB. By just looking at these numbers, a run of 60min equates to 15.8GB -> 7.9GB reduction in log size.

Set log recording period

---

mbzirc_ign/src/Wavefield.cc

Follow up to https://github.com/osrf/mbzirc/pull/206 that added a service for requesting global wavefield params. This PR adds a `Recalculate()` call so that the wavefield changes actually take place. This should only affect the `coast_cloud` world which has `wavefield` param specified in `GameLogicPlugin`

Recalculate wavefield values when service call succeeds

---

mbzirc_ign/src/GameLogicPlugin.cc

fixes https://github.com/osrf/mbzirc/issues/209.
Problem was that rgbd camera does not support the `VisualAt` function that is used to identify targets. I worked around the issue by creating a regular camera with the rgbd camera's resolution and hfov, which is used in place of the rgbd camera when a target report is received.
Steps for testing are similar to https://github.com/osrf/mbzirc/pull/195. Instead of using an `mbzirc_hd_camera`, use an `mbzirc_rgbd_camera`. The rgbd camera has lower resolution so when reporting targets, change coordinates to `320`, `240`

Fix reporting targets from RGBD camera
